fabsalito_blog_homepage:
    pattern:  /
    defaults: { _controller: fabsalitoBlogBundle:Page:index }
    requirements:
        _method:  GET

fabsalito_blog_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: fabsalitoBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

fabsalito_blog_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: fabsalitoBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+
