parameters:
#    fabsalito_blog.example.class: fabsalito\BlogBundle\Example

services:
#    fabsalito_blog.example:
#        class: %fabsalito_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    fabsalito_blog.twig.extension:
        class: fabsalito\BlogBundle\Twig\Extension\BlogExtension
        tags:
            - { name: twig.extension }
