parameters:
    database_driver:    pdo_mysql
    database_host:      127.0.0.1
    database_port:      null
    database_name:      fabsalito
    database_user:      fabsalito
    database_password:  Franca1621

    mailer_transport:   smtp
    mailer_host:        127.0.0.1
    mailer_user:        ~
    mailer_password:    ~

    locale:             en
    secret:             dfe25e105ca910510d9a182d8f9c3c49100e
    database_path:      null
