frontend_homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:Default:index }

frontend_about:
    pattern:  /about
    defaults: { _controller: FrontendBundle:Default:about }
    requirements:
        _method:  GET

frontend_contact:
    pattern:  /contact
    defaults: { _controller: FrontendBundle:Default:contact }
    requirements:
        _method:  GET|POST