parameters:
#    frontend.example.class: fabsalito\FrontendBundle\Example

services:
#    frontend.example:
#        class: %frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    fabsalito_frontend_main.menu_builder:
        class: fabsalito\FrontendBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    fabsalito_frontend_main.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: fabsalito_frontend_main.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: frontend_main } # The alias is what is used to retrieve the menu
