parameters:
#    frontend.example.class: fabsalito\FrontendBundle\Example

services:
#    frontend.example:
#        class: %frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
